name: Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "Q003"
          max-line-length: "120"

